ulmfit={
    "r/politics":"https://www.googleapis.com/drive/v3/files/1kncQ_Nt-LHfGQrIAF_tlmgyVkuIRwqNO?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/aww":"https://www.googleapis.com/drive/v3/files/1HGImIPGbmCWdlbB22jz9VHq7XN5wCcE5?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/conservative":"https://www.googleapis.com/drive/v3/files/1b8HqdLnIBSQC2xb2R6Gvg912-hKkqaJ7?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/democrat":"https://www.googleapis.com/drive/v3/files/1yilHFGWOhxeG-1h7GVk7IKQoZ3ObW9FA?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/elizabethwarren":"https://www.googleapis.com/drive/v3/files/18CHmBWAFTmbStg-pX2o5Ek8BrSQkAzj_?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/impeach_trump":"https://www.googleapis.com/drive/v3/files/1OW2xBtk0qfLAZrUNo2a8GiKQj1XrkcCR?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/libertarian":"https://www.googleapis.com/drive/v3/files/1tlKoCldJNPHQkFoAnqlf7edh-DOhg5fT?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/news":"https://www.googleapis.com/drive/v3/files/1v9Ziz-ED3FDzGzYALxc3_uo1B4qpC-Aq?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/ourpresident":"https://www.googleapis.com/drive/v3/files/1Vjur6lKPBAcsazRSSqfb9aqWnPVmaiMH?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/sandersforpresident":"https://www.googleapis.com/drive/v3/files/1b1RYwHiHpK9Z5xMti0sDlaCGILcxyKFn?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/soccer":"https://www.googleapis.com/drive/v3/files/1FxQZkpfY85JVmQSi4PlYkYeViAHBv6DN?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/the_donald":"https://www.googleapis.com/drive/v3/files/1idezm1acnE8cwLB74heHsP8aS8KfoEZM?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/the_mueller":"https://www.googleapis.com/drive/v3/files/1z3PHo4UaBlGLc20kMYA7dkd0I4tAkJ-3?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/yangforpresidenthq":"https://www.googleapis.com/drive/v3/files/1vu8SkmqpAb3leD3gMtfNKLQGd0nqhceA?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU"
}

gpt2={
    "r/politics":'https://www.googleapis.com/drive/v3/files/1m4zD09JvOhG_7k0ovikIs7W5eB1oqJuY?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU',
    "r/aww":"https://www.googleapis.com/drive/v3/files/1J9RlWlCyRq28T6eFB4euw6TEaq7IEApy?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/conservative":"https://www.googleapis.com/drive/v3/files/1AW1ug-JabrCV01dsHJnn1WvN1QeRVRaa?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/democrat":"https://www.googleapis.com/drive/v3/files/1pt9ywVWnEImv5CEGoGSCefdBLplw-ynU?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/elizabethwarren":"https://www.googleapis.com/drive/v3/files/1WLfNNN4v3QcuM9aPnL4xfPM3vg4M38ZJ?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/impeach_trump":"https://www.googleapis.com/drive/v3/files/19sY-wmWEdVfRnC7fScBmSVpA315VqTZ1?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/libertarian":"https://www.googleapis.com/drive/v3/files/1OJPvO34KDdf8rmsGPGuH0_jndeVRrIT7?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/news":"https://www.googleapis.com/drive/v3/files/1jQXh1PCSHd4Aq12mWfXmh_98OOtuaIU5?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/sandersforpresident":"https://www.googleapis.com/drive/v3/files/15wnfwF2xI_8Pv190izrvB8V0gGiTXwqB?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/soccer":"https://www.googleapis.com/drive/v3/files/146gYOaY7ppHpxkw8AUa2Rh9VJdADFsSu?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/yangforpresidenthq":"https://www.googleapis.com/drive/v3/files/1ZxT19x8jAd94vQKHtyb3T2VWrltIOl4q?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/the_mueller":"https://www.googleapis.com/drive/v3/files/1N8FVZnLpUVLgFSDP3AGsWCKPCzb_jJlY?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/the_donald":"https://www.googleapis.com/drive/v3/files/1QZTLjXUSoCSOmf56axZS4e2JmNXN1OzQ?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU",
    "r/ourpresident":"https://www.googleapis.com/drive/v3/files/1wx831hUTQ81BjdizjWRtYtMsKVG5raa8?alt=media&key=AIzaSyCwAreaXcbtPfMsDQRpwLgS0uKNWxxvhKU"
}